### PR TITLE
Pre-release v0.4.3 (#264)

### PR DESCRIPTION
**Pull request by yohanchatelain**

### CODE REVIEW

**Review by pablooliveira — APPROVED** [review]
This look complete. Thanks for updating the CHANGELOG !

I think it would be good practice to update the CHANGELOG, step by step for each PR merged. I know that is what @yohanchatelain has already being doing; but I think it would be nice if we all try to do it in the future.

**Review by pablooliveira — CHANGES_REQUESTED** [review]
Actually before you merge, I think there are a few big changes and improvements in this release.

Maybe we should increase the major version number since this is clearly more than an incremental release. I think we could have v0.5.0 instead.

Moreover the CI workflow tool from @PurplePachyderm is quite a big project; maybe we could have a slightly longer description to help the user discover it. I would suggest:

* Add vfc_ci, a new tool which integrates verificarlo in a CI workflow and generates interactive reports that track numerical errors across the project lifetime.

**Comment by pablooliveira** [comment]
Sorry @yohanchatelain, I added my request for changes a bit late.

**Comment by yohanchatelain** [comment]
Sorry I already merged the PR but I changed the release state to pre-release so we can still modify it.

**Comment by yohanchatelain** [comment]
Btw, you could enable the discussion sections on verificarlo like I did in [sigdigits](https://github.com/verificarlo/significantdigits/discussions), to have a dedicated space to discuss without opening issues.

**Comment by titeup** [comment]
I agree with Pablo comment, 0.5 is preferable.
I even think that the project start to be mature enough to reach 1.0 ;) (with relicensing)
Also there have been some addition in the documentation (ci in particular) so I would add this bullet in the addition (and maybe fused the changed in the doc in the same bullet on top)
I cannot see Matei's fix/changes in func instr and vprec-libm exploration in your list but maybe he did not push it on master yet. I will check with him. It would be nice to have it release so he can claim it in his funded project review.

**Pull request merged**
