### PR TITLE
Make verificarlo compatible with LLVM up to 3.8

### PR DESCRIPTION
**Pull request by pablooliveira**
This pull request makes Verificarlo compatible with LLVM versions up to 3.8 and keeps the code backwards compatible with LLVM versions as old as 3.3.

It also fixes an annoying bug with clang detection on ubuntu and debian systems. Now it should not be necessary anymore to add a symlink to clang when installing verificarlo.

### CODE REVIEW

**Comment by titeup** [comment]
I will try on my system.

**Comment by pablooliveira** [comment]
There seems to be a bug with older versions in the travis build. I'm working on it, will report back.

**Comment by pablooliveira** [comment]
Seems to work now :-) Could you please review and merge.

**Comment by titeup** [comment]
ok I'll pull and try on majorque

**Comment by titeup** [comment]
make[3]: Entering directory '/home/epetit/verificarlo_master/verificarlo/src/libvfcinstrument'
  CXX      libvfcinstrument_la-libVFCInstrument.lo
libVFCInstrument.cpp: In member function ‘llvm::Instruction* {anonymous}::VfclibInst::replaceWithMCACall(llvm::Module&, llvm::BasicBlock&, llvm::Instruction*, {anonymous}::Fops)’:
libVFCInstrument.cpp:34:47: error: ‘class llvm::IRBuilder<>’ has no member named ‘CreateCall2’
 #define CREATE_CALL2(func, op1, op2) (builder.CreateCall2(cast<Function>(func), op1, op2, ""))
                                               ^
libVFCInstrument.cpp:187:40: note: in expansion of macro ‘CREATE_CALL2’
                 Instruction *newInst = CREATE_CALL2(hookFunc,
                                        ^
libVFCInstrument.cpp:35:65: error: no matching function for call to ‘llvm::IRBuilder<>::CreateStructGEP(llvm::Constant*&, int&)’
 #define CREATE_STRUCT_GEP(t, i, p) (builder.CreateStructGEP(i, p))
                                                                 ^
libVFCInstrument.cpp:214:34: note: in expansion of macro ‘CREATE_STRUCT_GEP’
                 Value *arg_ptr = CREATE_STRUCT_GEP(mca_interface_type, current_mca_interface, fct_position);
                                  ^
In file included from libVFCInstrument.cpp:27:0:
/usr/lib/llvm-3.8/include/llvm/IR/IRBuilder.h:1240:10: note: candidate: llvm::Value* llvm::IRBuilder<preserveNames, T, Inserter>::CreateStructGEP(llvm::Type*, llvm::Value*, unsigned int, const llvm::Twine&) [with bool preserveNames = true; T = llvm::ConstantFolder; Inserter = llvm::IRBuilderDefaultInserter<true>]
   Value *CreateStructGEP(Type *Ty, Value *Ptr, unsigned Idx,
          ^
/usr/lib/llvm-3.8/include/llvm/IR/IRBuilder.h:1240:10: note:   candidate expects 4 arguments, 2 provided
libVFCInstrument.cpp:34:47: error: ‘class llvm::IRBuilder<>’ has no member named ‘CreateCall2’
 #define CREATE_CALL2(func, op1, op2) (builder.CreateCall2(cast<Function>(func), op1, op2, ""))
                                               ^
libVFCInstrument.cpp:222:40: note: in expansion of macro ‘CREATE_CALL2’
                 Instruction *newInst = CREATE_CALL2(
                                        ^
libVFCInstrument.cpp: In member function ‘bool {anonymous}::VfclibInst::runOnBasicBlock(llvm::Module&, llvm::BasicBlock&)’:
libVFCInstrument.cpp:254:75: error: no matching function for call to ‘{anonymous}::VfclibInst::replaceWithMCACall(llvm::Module&, llvm::BasicBlock&, llvm::BasicBlock::iterator&, {anonymous}::Fops&)’
                 Instruction *newInst = replaceWithMCACall(M, B, ii, opCode);
                                                                           ^
libVFCInstrument.cpp:139:22: note: candidate: llvm::Instruction* {anonymous}::VfclibInst::replaceWithMCACall(llvm::Module&, llvm::BasicBlock&, llvm::Instruction*, {anonymous}::Fops)
         Instruction *replaceWithMCACall(Module &M, BasicBlock &B, Instruction * I, Fops opCode) {
                      ^
libVFCInstrument.cpp:139:22: note:   no known conversion for argument 3 from ‘llvm::BasicBlock::iterator {aka llvm::ilist_iterator<llvm::Instruction>}’ to ‘llvm::Instruction*’

**Comment by titeup** [comment]
and with 3.6 it still works

**Comment by titeup** [comment]
(except the fortran test on majorque, dragonegg install  issue)

**Comment by pablooliveira** [comment]
Which version of LLVM did it fail with on majorque ?

**Comment by titeup** [comment]
3.8

**Comment by chdenis** [comment]
Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)
Target: x86_64-pc-linux-gnu
Thread model: posix

============================================================================
Testsuite summary for verificarlo 0.1.0
============================================================================
# TOTAL: 7
# PASS:  7

**Comment by pablooliveira** [comment]
Thanks, there was still some problems with API changes to CreateStructGEP in 3.7. I tested on my system and tests are green with 3.4, 3.5, 3.7 and 3.8.

If everything is fine on your side could you please approve the review and merge.

**Comment by titeup** [comment]
fails on majorque with 3.6 (simpilar API issue), and with 3.8 with a new error.

**Comment by titeup** [comment]
make[2]: Entering directory '/home/epetit/verificarlo_master/verificarlo/src/libvfcinstrument'
  CXX      libvfcinstrument_la-libVFCInstrument.lo
  CXXLD    libvfcinstrument.la
ar: `u' modifier ignored since `D' is the default (see `U')
make[3]: Entering directory '/home/epetit/verificarlo_master/verificarlo/src/libvfcinstrument'
 /bin/mkdir -p '/usr/local/lib'
 /bin/bash ../../libtool   --mode=install /usr/bin/install -c   libvfcinstrument.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libvfcinstrument.so.0.0.0 /usr/local/lib/libvfcinstrument.so.0.0.0
/usr/bin/install: cannot create regular file '/usr/local/lib/libvfcinstrument.so.0.0.0': Permission denied
Makefile:377: recipe for target 'install-libLTLIBRARIES' failed
make[3]: *** [install-libLTLIBRARIES] Error 1
make[3]: Leaving directory '/home/epetit/verificarlo_master/ve

**Comment by titeup** [comment]
and with 3.6 the older error but the other way:

make[2]: Entering directory '/home/epetit/verificarlo_master/verificarlo/src/libvfcinstrument'
  CXX      libvfcinstrument_la-libVFCInstrument.lo
libVFCInstrument.cpp: In member function ‘llvm::Instruction* {anonymous}::VfclibInst::replaceWithMCACall(llvm::Module&, llvm::BasicBlock&, llvm::Instruction*, {anonymous}::Fops)’:
libVFCInstrument.cpp:37:78: error: no matching function for call to ‘llvm::IRBuilder<>::CreateCall(llvm::Constant*&, <brace-enclosed initializer list>, const char [1])’
 #define CREATE_CALL2(func, op1, op2) (builder.CreateCall(func, {op1, op2}, ""))
                                                                              ^
libVFCInstrument.cpp:187:40: note: in expansion of macro ‘CREATE_CALL2’
                 Instruction *newInst = CREATE_CALL2(hookFunc,
                                        ^
In file included from libVFCInstrument.cpp:27:0:
.....

**Comment by titeup** [comment]
make 
sudo make install works
but then all the test but the first failed during make check

**Comment by titeup** [comment]
it works!

**Comment by pablooliveira** [comment]
Great thanks for the review !

**Pull request merged**
