### PR TITLE
removing the clean of tests/paths.sh file

### PR DESCRIPTION
**Pull request by Sholde**
This file was generated by the configuration script before. But now it
have a default setting.

### CODE REVIEW

**Comment by Sholde** [comment]
But this default setting depends on the architecture?
For example me, I don't have `llvm-7`, so this setting is obsolete for me?

**Comment by yohanchatelain** [comment]
I think we should remove `tests/path.sh` file from the tracked file because we don't have default setting. Maybe it has been tracked by mistake. This file must be generated by the configure.

**Comment by Sholde** [comment]
Agreed. I think I will make another PR.

**Comment by yohanchatelain** [comment]
You can just untracked the file and push a new commit.

**Review by yohanchatelain — APPROVED** [review]

**Pull request merged**
