### PR TITLE
Absolute error

### PR DESCRIPTION
**Pull request by pablooliveira**
This is a rebase cleanup of @mistoan work in PR #173, which contains the full history.
The commit granularity in PR #173 was high, this new PR reduces the commit history before merging. 

Thanks @mistoan for a great work on absolute error options for vprec and mca. The last factorings make things quite elegant. The works looks very nice and is ready to merge.

### CODE REVIEW

**Comment by pablooliveira** [comment]
@mistoan since I did the last cleanup, I cannot merge myself per repository rules. I let you merge this yourself :tada: You can do an approving review and merge directly after. If you wish to change something, you can push changes to this branch which is hosted on verificarlo/absoluteError.

**Review by yohanchatelain — APPROVED** [review]
LGTM, good work :tada: 
Maybe the tests could be refactored later to be easier to read.

**Review by mistoan — COMMENTED** [review]
The original merge request had, indeed, a cluttered history of commits.
This is much clearer.
Thank you!

The code looks

**Comment by mistoan** [comment]
> LGTM, good work tada
> Maybe the tests could be refactored later to be easier to read.

Agreed, some refactoring of the tests should help with readability, in the longterm.

**Pull request merged**
