### PR TITLE
Updated TargetLibraryInfo call.  Otherwise, library calls aren't inte…

### PR DESCRIPTION
**Pull request by roblim1**
…rcepted.

### CODE REVIEW

**Comment by mistoan** [comment]
> @mistoan this could be related to the missing `sqrt` call you observed on PATMOS analysis with FuncInstrument ?

I'm not sure.
Does this actually provide more up-to-date information?
The pass isn't redone, but I might be missing something.

> 
> @roblim1 I think this looks nice and can be merged. Could you provide a bit of context to document before we merge ? Which particular library call were you missing before this fix ?
> 
> Thanks

**Comment by roblim1** [comment]
Actually, I have another pass that does this detection and will update the PR shortly.  Thanks.

**Comment by roblim1** [comment]
Branch updated.  Also,I think there needs to be logic here to make this work:

https://github.com/verificarlo/verificarlo/blob/1f9d7f22fbb5258aa9fc043da919c90f8df43e79/src/libvfcfuncinstrument/libVFCFuncInstrument.cpp#L539

**Comment by roblim1** [comment]
Branch updated.  Also, I think there needs to be logic here to make this work:

https://github.com/verificarlo/verificarlo/blob/1f9d7f22fbb5258aa9fc043da919c90f8df43e79/src/libvfcfuncinstrument/libVFCFuncInstrument.cpp#L539

**Comment by roblim1** [comment]
Branch updated.  Also,I think there needs to be logic here to make this work:

https://github.com/verificarlo/verificarlo/blob/1f9d7f22fbb5258aa9fc043da919c90f8df43e79/src/libvfcfuncinstrument/libVFCFuncInstrument.cpp#L539

**Comment by roblim1** [comment]
Branch updated.  Also, I think there needs a check here to make this work:

https://github.com/verificarlo/verificarlo/blob/1f9d7f22fbb5258aa9fc043da919c90f8df43e79/src/libvfcfuncinstrument/libVFCFuncInstrument.cpp#L539

**Comment by roblim1** [comment]
Branch updated.  Also, I think there needs to be a check here to make this work:

  https://github.com/verificarlo/verificarlo/blob/1f9d7f22fbb5258aa9fc043da919c90f8df43e79/src/libvfcfuncinstrument/libVFCFuncInstrument.cpp#L539

**Comment by roblim1** [comment]
Library pass done.  I could produce a case where Verificarlo fails with the current implementation with respect to library calls.

**Comment by pablooliveira** [comment]
Thanks @roblim1, could you please provide a short test so that I can test this before merging it ?

**Comment by roblim1** [comment]
Ok, never mind.  The current implementation detects library calls fine.  In my case, I needed to update [haveFloatingPointArithmetic()](https://github.com/verificarlo/verificarlo/blob/master/src/libvfcfuncinstrument/libVFCFuncInstrument.cpp#L70) to detect floats and doubles from derived types. Thanks.

**Pull request closed without merging**
