### PR TITLE
Verificarlo can be installed system wide

### PR DESCRIPTION
**Pull request by pablooliveira**
With this PR verificarlo can (and must) be installed with `make
install`. This is a prerequisite for #12.

### CODE REVIEW

**Comment by pablooliveira** [comment]
Hi all,

This PR makes verificarlo installable system wide. If we merge it, we can install verificarlo with make install :-)

Take care when testing this patch, now you have to do "sudo make install" before using verificarlo or running "make check".

Once it is merged, we then can prepare a debian and ubuntu package for verificarlo.
Could you please review and merge.

Thanks :tada:

**Comment by titeup** [comment]
make[3]: Entering directory '/home/epetit/verificarlo_master/verificarlo/tests'
PASS: testplan.test 1 ./test_accsum
FAIL: testplan.test 2 ./test_backends
FAIL: testplan.test 3 ./test_ffastmath
PASS: testplan.test 4 ./test_fortran
FAIL: testplan.test 5 ./test_kahan
PASS: testplan.test 6 ./test_per_function
FAIL: testplan.test 7 ./test_tchebychev

I will look in more details.

**Comment by pablooliveira** [comment]
Take care, depending on where you install the libraries you may have to export the target library dir in LD_LIBRARY_PATH. (Usually you have a message about this during make install)

export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

**Comment by titeup** [comment]
make[3]: Entering directory '/home/epetit/verificarlo_master/verificarlo/tests'
PASS: testplan.test 1 ./test_accsum
PASS: testplan.test 2 ./test_backends
PASS: testplan.test 3 ./test_ffastmath
PASS: testplan.test 4 ./test_fortran
PASS: testplan.test 5 ./test_kahan
PASS: testplan.test 6 ./test_per_function
PASS: testplan.test 7 ./test_tchebychev

my fault...

**Comment by pablooliveira** [comment]
It is :-) See change in Readme.md

**Comment by pablooliveira** [comment]
Thanks for the review !

**Pull request merged**
