### PR TITLE
Use double for single operation

### PR DESCRIPTION
**Pull request by titeup**
Hi, 

Forgot to fork before working, so I crete a new branch and create a pull request from there.
I hope it is an 'ok' procedure ;)

Cheers,

Eric

### CODE REVIEW

**Comment by titeup** [comment]
Hi,

DO NOT MERGE!

Info: I commited the version with the bug, I have no idea yet way it is failling on the function test, facts:
- I only change single prec wrapper and this test is double
- When testing my last changes adding printf to the operator for single prec management, the test works. (this is why Travis is happy while it shouldn't) => DO NOT MERGE!
-This function with printf are not even called => might be a mem alloc problem solved by having allocated memory for the printf format string
Still working on it...

**Comment by titeup** [comment]
Actually I guessed what happen while writing the last comment ;) Bug fixed ;)
However I still do not understand why this specific test failled because of it... And I will probably never know...

**Comment by titeup** [comment]
Last commit tonight.
I finally replaced the quad multiplication by bits operation since one of the operand is a power of 2.
However I suppose because I don't have ieee roundind and conversion during the operation wich means that the lowest bits (up to ~4 empirically)might change in both direction. This must be checked and validated.
Good news however, the final speed up on ingle precision is 35, and 4 on double precision (formerly 3 and 3)

**Comment by pablooliveira** [comment]
I'm sorry ! I messed up when trying to contribute to your PR. I accidentally deleted this branch. I have restored it but apparently github does not allow to reopen a PR once its original branch has been deleted... We can continue discussion at #7.

**Pull request closed without merging**
